---
title: "fig_ss_irregularities"
author: "Josh Alampi"
date: "10/25/2021"
output: html_document
---

```{r}
#clear workspace
rm(list=ls(all=TRUE))

#load packages
library(readr); library(writexl) # for read_csv(); write_xlsx()
library(plyr) # mapvalues()
library(MASS)
library(dplyr)
library(tidyr) # for gather()
library(ggplot2)
library(ggrepel); library(ggpubr); library(scales) # extra ggplot features
library(signs) # for signs_format(), uses proper minus sign instead of hyphen
library(lmtest) # for bptest()
library(quantreg)
library(bayesQR)
select <- dplyr::select
library(rstan)
source("functions/ggplot functions.R")

is_integer <- name <- function(x) {
  response <- F
  if(abs(x) %% 1 < 1e-13) {
    response <- T 
  }
  return(response)
}


```

# load
```{r}
data_nodith <- read.csv("sim study/raw results/table_ss_no dith_v2_2021-08-04_1000_sims.csv")
data_dith <- read.csv("sim study/raw results/table_ss_JA model_2021-08-07_1000_sims.csv")
data_gold <- read.csv("sim study/raw results/table_ss_JA moel_gold_2021-10-28_1000_sims.csv")

nrow(data_nodith)
nrow(data_dith)
nrow(data_gold)

```


# clean v2
## no dith
```{r}
data_nodith <- data_nodith %>% 
  filter(method %in% c("iid", "riid", "rnid")) %>% 
  mutate(dithered = F) %>% 
  mutate(gold = F)

# give the model variable proper names
data_nodith$model <- data_nodith$model %>% # give the models proper names
  mapvalues(1, "Model 1") %>% 
  mapvalues(2, "Model 2") %>% 
  mapvalues(3, "Model 3") %>% 
  mapvalues(4, "Model 4") 

nrow(data_nodith)
```

## dith
```{r}
data_dith <- data_dith %>% 
  filter(method != "bayes_adj_v1") # do not need adj_v1 (the default SW adjustment), as I have demonstrated earlier that it is defective. 

data_dith$method <- data_dith$method %>% # rename the Bayesian methods
  mapvalues("bayes_adj_v2", "BayesQR (adj)") %>% 
  mapvalues("bayes", "BayesQR") 

data_dith <- data_dith %>% 
  mutate(dithered = ifelse(method %in% c("BayesQR (adj)", "BayesQR"),
                           F, # Bayesian methods were not dithered
                           T)) %>%  # Frequentist methods were dithered
  mutate(gold = F)

# give the model variable proper names
data_dith$model <- data_dith$model %>% # give the models proper names
  mapvalues(1, "Model 1") %>% 
  mapvalues(2, "Model 2") %>% 
  mapvalues(3, "Model 3") %>% 
  mapvalues(4, "Model 4") 
```

## gold
```{r}
data_gold <- data_gold %>% 
  filter(is.na(method) == F) %>% # gets rid of blank method rows
  mutate(dithered = F) %>% 
  mutate(gold = T)

# give the model variable proper names
data_gold$model <- data_gold$model %>% # give the models proper names
  mapvalues(1, "Model 1") %>% 
  mapvalues(2, "Model 2") %>% 
  mapvalues(3, "Model 3") %>% 
  mapvalues(4, "Model 4") 
```


## combine
```{r}
data <- rbind(data_dith, data_nodith); nrow(data)
data <- rbind(data, data_gold); nrow(data)
rm(data_dith, data_nodith, data_gold)
```



## prep for analysis
```{r}
data$beta <- as.numeric(data$beta)
data$lb <- as.numeric(data$lb)
data$ub <- as.numeric(data$ub)
data$tau <- as.factor(data$tau)


# Calculate performance measures 
data1 <- data %>%
  mutate(n = paste0(("n = "), n)) %>% 
  
  # Detecting irregular results
  mutate(degen_flag = ifelse(beta == lb | beta == ub,
                             T, # interval is degenerate
                             F) ) %>%
  mutate(infin_flag = ifelse(is.infinite(lb) == T | is.infinite(ub) == T,
                             T, # interval is infinite
                             F) ) %>%
  # mutate(integ_flag = ifelse(is_integer(beta) == T,
  #                            T, # beta is an integer
  #                            F) )
  mutate(integ_flag = ifelse(beta < 1e-13 & beta > -1e-13,
                             T, # beta is an integer
                             F) ) %>% 
  mutate(either_flag = ifelse(degen_flag == T | infin_flag == T,
                             T, # interval is infinite or degenerate 
                             F) ) 
  

# for(i in 1:nrow(data1)){
#   ifelse(is_integer(data1[i,2]) == T,
#          data1[i,12] <-  T,
#          data1[i,12] <-  F)
# }


# data1 <- data %>% 
#   mutate(both_flag = ifelse(degen_flag == T & integ_flag == T))

data1$method <- factor(data1$method,levels= c("iid", "nid", "ker", "riid", "rnid", 
                                            "xy", "wxy", "pwy", "mcmb", "wild", "pbs", 
                                            "BayesQR", "BayesQR (adj)") )
```

# Make figure 1: mod 1
## prep
```{r}
data_hist <- data1 %>% 
  filter(n == "n = 250") %>% 
  filter(model == "Model 1") %>% 
  filter(method %in% c("iid", "BayesQR"))

data_hist_bayes <- data_hist %>% 
  filter(method == "BayesQR") %>% 
  mutate(method_final = 4) %>% 
  select(-c(method, dithered, gold))

data_hist_freq <- data_hist %>% 
  filter(method == "iid") %>% 
  mutate(method_final = ifelse(dithered == T & gold == F, # change method labels
                         3,
                         ifelse(dithered == F & gold == F,
                                2,
                                ifelse(dithered == F & gold == T,
                                       1,
                                       NA))))%>% 
  select(-c(method, dithered, gold))

data_hist <- rbind(data_hist_freq, data_hist_bayes); nrow(data_hist)
rm(data_hist_bayes, data_hist_freq)

data_hist_50 <- data_hist %>% 
  filter(tau == 0.5)

data_hist_90 <- data_hist %>% 
  filter(tau == 0.9)

data_hist_10 <- data_hist %>% 
  filter(tau == 0.1)

text_size_minor <- 8
text_size_major <- 9
text_size_title <- 10
x_angle <- 0
```

```{r}
title_a <- (paste(
  "A) Frequentist quantile regression on \ncontinuous Y variable without dithering"))

title_b <- (paste(
  "B) Frequentist quantile regression on \ncount Y variable without dithering"
  ))

title_c <- (paste(
  "C) Frequentist quantile regression on \ncount Y variable with dithering"
  ))

title_d <- (paste(
  "D) Bayesian quantile regression on \ncount Y variable without dithering"
  ))


```

## tau = 0.5
```{r}
a <- data_hist_50 %>% 
  filter(method_final == 1) %>% 
  ggplot(aes(x=beta)) +
  geom_histogram(bins = 40, color="black", fill="white") +
  labs(title=title_a,
       x="Point estimate", y = "Frequency") + 
  theme_bw() +
  theme(text = element_text(family = "sans", colour = "black", size = text_size_minor)) +
  theme(axis.text.x = element_text(size=text_size_minor, colour = "black", angle = x_angle)) + 
  theme(axis.text.y = element_text(size=text_size_minor, colour = "black")) + 
  theme(axis.ticks = element_line(size = 0.5, colour = "black")) + 
  theme(axis.title.x = element_text(size=text_size_major, colour = "black")) + 
  theme(axis.title.y = element_text(size=text_size_major, colour = "black")) +
  theme(title = element_text(size = text_size_title, colour = "black")) 

b <- data_hist_50 %>% 
  filter(method_final == 2) %>% 
  ggplot(aes(x=beta)) +
  geom_histogram(bins = 40, color="black", fill="white") +
  labs(title=title_b,
       x="Point estimate", y = "Frequency") + 
  theme_bw() +
  theme(text = element_text(family = "sans", colour = "black", size = text_size_minor)) +
  theme(axis.text.x = element_text(size=text_size_minor, colour = "black", angle = x_angle)) + 
  theme(axis.text.y = element_text(size=text_size_minor, colour = "black")) + 
  theme(axis.ticks = element_line(size = 0.5, colour = "black")) + 
  theme(axis.title.x = element_text(size=text_size_major, colour = "black")) + 
  theme(axis.title.y = element_text(size=text_size_major, colour = "black")) +
  theme(title = element_text(size = text_size_title, colour = "black")) 

c <- data_hist_50 %>% 
  filter(method_final == 3) %>% 
  ggplot(aes(x=beta)) +
  geom_histogram(bins = 40, color="black", fill="white") +
  labs(title=title_c,
       x="Point estimate", y = "Frequency") + 
  theme_bw() +
  theme(text = element_text(family = "sans", colour = "black", size = text_size_minor)) +
  theme(axis.text.x = element_text(size=text_size_minor, colour = "black", angle = x_angle)) + 
  theme(axis.text.y = element_text(size=text_size_minor, colour = "black")) + 
  theme(axis.ticks = element_line(size = 0.5, colour = "black")) + 
  theme(axis.title.x = element_text(size=text_size_major, colour = "black")) + 
  theme(axis.title.y = element_text(size=text_size_major, colour = "black")) +
  theme(title = element_text(size = text_size_title, colour = "black")) 

d <- data_hist_50 %>% 
  filter(method_final == 4) %>% 
  ggplot(aes(x=beta)) +
  geom_histogram(bins = 40, color="black", fill="white") +
  labs(title=title_d,
       x="Point estimate", y = "Frequency") + 
  theme_bw() +
  theme(text = element_text(family = "sans", colour = "black", size = text_size_minor)) +
  theme(axis.text.x = element_text(size=text_size_minor, colour = "black", angle = x_angle)) + 
  theme(axis.text.y = element_text(size=text_size_minor, colour = "black")) + 
  theme(axis.ticks = element_line(size = 0.5, colour = "black")) + 
  theme(axis.title.x = element_text(size=text_size_major, colour = "black")) + 
  theme(axis.title.y = element_text(size=text_size_major, colour = "black")) +
  theme(title = element_text(size = text_size_title, colour = "black")) 

hist_50 <- ggarrange(a, b, c, d, nrow = 2, ncol = 2)
hist_50

# ggsave(file = paste0("sim study/results/irreg/hist of beta_mod1_n250_tau50",
#                      "_",  Sys.Date(), ".png"), 
#        width = 7.5, height = 5, dpi = 300)

ggsave(file = paste0("sim study/results/figure 1.tiff"), 
       width = 7.5, height = 5, dpi = 600)

```





